version: "3.8"

services:
  web:
    image: node
    command: sh -c "npm install && npm run start"
    working_dir: /memo-backend
    volumes:
      - ./:/memo-backend
    ports:
      - "3000:3000"
    environment:
      POSTGRES_URI: postgres://root:root@postgres:5432/root
      REDIS_URI: redis://redis:6379
      JWT_SECRET: "${JWT_SECRET}"
  postgres:
    build: ./postgres
    restart: always
    environment:
      - POSTGRES_USER=root #TODO can i remove it?
      - POSTGRES_PASSWORD=root #TODO can i remove it?
      - POSTGRES_DB=root #TODO can i remove it?
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  # PostgreSQL pgAdmin panel accessible at http://localhost:16543/
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "q@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "qwe"
    ports:
      - "16543:80"
    depends_on:
      - postgres
  redis:
    image: redis
    ports:
      - "6379:6379"
